server:
  port: 8080


spring:
  data:
    mongodb:
#      username: project-user
#      password: user123
#      privileges: read-only
      uri: mongodb+srv://project-user:user123@cluster0.f4iopv1.mongodb.net/project-integracja-systemow?retryWrites=true&w=majority
